### ISSUE TITLE
Add support for connecting to the Firestore Emulator

### ISSUE THREAD

**Issue by thebitguru** [prescottprue/fireadmin#103]
## Description Of Potential Feature
I tried putting in http://localhost:8080 in the database URL field, but it kept refusing it so I am assuming connecting to [Firestore emulator](https://firebase.google.com/docs/emulator-suite/connect_and_prototype?hl=en) is not currently supported.  It would be great if we can get this support.

## Additional Issues This May/Does Solve
Better local development.

**Comment by prescottprue** [comment]
Thanks for reaching out! It is supported by doing `yarn emulate:dbs` then calling `yarn start:emulate` in another terminal window. The goal was to have `yarn dev` do this in a single command, but it appears to not be working currently.

This is in npm scripts since it is done through environment variables [here within createStore](https://github.com/prescottprue/fireadmin/blob/master/src/store/createStore.js#L69).

Something else of note: There is [currently a large rewrite going on](https://github.com/prescottprue/fireadmin/pull/102) to remove redux so some of that logic will move around, but the plan is just change internals to simplify things, so hopefully isn't too jarring

**Comment by thebitguru** [comment]
Ah, I see.  I will play around with that.  Thanks for creating this project!
