### ISSUE TITLE
Question: avoiding gRPC errors with Cypress

### ISSUE THREAD

**Issue by bpkennedy** [prescottprue/fireadmin#80]
Hello, glad to find this library!  I spent about a couple days trying to figure out why I couldn't get my cypress tests to run.  I opened an issue on the Cypress repo (https://github.com/cypress-io/cypress/issues/3570), but ultimately ended up trying TestCafe which is having it's own issues getting gitlabCI running correctly.  Honestly, I preferred the sensibilities of Cypress and want to try again.

Can you help with this issue?  It appears that your library is mostly for manually calling into Firebase/Firestore *within the test*.  I would like my tests to be purely concerned with clicking and expecting the interface to change.  Just like the real app, there is no manually POSTing or GETing during the tests.  Do you have examples like that?

To clarify, it would be a test like:
1. Cypress selects a button and clicks it.
2. App code makes a GET request to firestore, and returns data that the app uses to populate a list.
3. Cypress verifies the contents of the list.

**Comment by prescottprue** [comment]
@bpkennedy How does this relate to Fireadmin? Did you mean to post this on [cypress-firebase](https://github.com/prescottprue/cypress-firebase)?

**Comment by bpkennedy** [comment]
Ah, yes I did - my apologies.

**Comment by prescottprue** [comment]
Well you can do both - the two things you are describing are often referred to as the following
**"seeding"** - is adding/removing data from the database to prime it for a test that verifies the UI displays data correctly
**"verifying"** - checking the database to make sure the UI correctly updated based on clicks

It is common to have a test that mixes the two where you **seed** the database with something like a fake project, click a few buttons in the UI, maybe "delete project", then you **verify** that the delete action removes the data from the database.

It is taking a "round trip" or end-to-end approach since you are actually letting the UI write to the database and load data from the database that is placed there for tests.

**Comment by bpkennedy** [comment]
Ah, I see, thank you.  I see you have called the firebase initializeapp() in the cypress commands.js and then in your app you only initialize it if it doesn't already exist.  Is this because otherwise Cypress will throw gRPC errors during the Electron runtime?  (This is what I was running into when I first set it up).

**Comment by prescottprue** [comment]
@bpkennedy Well sort of - the instance is only initialized if it doesn't already exist because during the tests it is initialized and passed to the window. This works since Cypress shares a window with where the app is running.

The issues are seeing are common when trying to run certain node-modules within the Cypress environment since it is a browser (can be Electron like you mentioned). `firebase-admin` is one of those libraries since it uses gRPC. More is covered on this [in the why section of cypress-firebase](https://github.com/prescottprue/cypress-firebase#why).

If you are interested in starting with an app with this already setup, you may want to checkout [generator-react-firebase](https://github.com/prescottprue/generator-react-firebase). It has the option to include Cypress tests when creating your project - it will also include the stuff you need to run your tests in Gitlab.

Going to close this for now, but feel free to reach out over [gitter](https://gitter.im/redux-firestore/Lobby).
